const { Document, Packer, Paragraph, TextRun, AlignmentType, BorderStyle, ShadingType, LevelFormat, convertInchesToTwip } = require('docx');
const FS = 19;
const H1 = (t) => new Paragraph({ spacing: { before: 280, after: 110 }, shading: { type: ShadingType.CLEAR, fill: "8B0000" },
  children: [ new TextRun({ text: "  " + t, bold: true, size: 23, color: "FFFFFF" }) ] });
const H2 = (t) => new Paragraph({ spacing: { before: 180, after: 70 }, children: [ new TextRun({ text: t, bold: true, size: 20, color: "8B0000" }) ] });
const P = (runs) => new Paragraph({ spacing: { after: 100, line: 280 }, children: typeof runs === 'string' ? [ new TextRun({ text: runs, size: FS }) ] : runs });
const N = (runs) => new Paragraph({ numbering: { reference: "nums", level: 0 }, spacing: { after: 90, line: 275 }, children: typeof runs === 'string' ? [ new TextRun({ text: runs, size: FS }) ] : runs });
const B = (runs) => new Paragraph({ numbering: { reference: "bul", level: 0 }, spacing: { after: 70, line: 275 }, children: typeof runs === 'string' ? [ new TextRun({ text: runs, size: FS }) ] : runs });
const r = (t) => new TextRun({ text: t, size: FS });
const b = (t) => new TextRun({ text: t, bold: true, size: FS });
const i = (t) => new TextRun({ text: t, italics: true, size: FS });
const flag = (t) => new TextRun({ text: t, bold: true, size: FS, highlight: "yellow" });

const doc = new Document({
  numbering: { config: [
    { reference: "nums", levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT,
      style: { paragraph: { indent: { left: convertInchesToTwip(0.38), hanging: convertInchesToTwip(0.38) } } } }] },
    { reference: "bul", levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT,
      style: { paragraph: { indent: { left: convertInchesToTwip(0.25), hanging: convertInchesToTwip(0.18) } } } }] },
  ]},
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 720, bottom: 720, left: 900, right: 900 } } },
    children: [
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 20 },
        children: [ new TextRun({ text: "HEARING ANALYSIS — SEPTEMBER 10, 2026", bold: true, size: 30, color: "8B0000" }) ] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 20 },
        children: [ new TextRun({ text: "Case ZBA2026-055 (218 South Lincoln Street) and Case ZBA2026-063 (26 Titus Avenue)", bold: true, size: 20 }) ] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 170 },
        children: [ new TextRun({ text: "Internal working paper — not for filing. Prepared September 11, 2026.", italics: true, size: 16, color: "555555" }) ] }),

      H1("METHOD AND LIMITS"),
      P("This paper compares what was said at the two hearings against the written record before the Board. Source is the City's own recording of the September 10, 2026 meeting, machine-transcribed. Deliberations in both cases were transcribed twice, with a second and more accurate model, and every quotation below appears in both passes. Timestamps are hours:minutes from the start of the recording."),
      P([ flag("Two cautions."), r(" First, the transcript does not label speakers. Attributions below rest on the Chair addressing members by first name and on members referring to one another. Each attribution should be confirmed against the video before any of this is filed. Second, one passage is marked as uncertain where the two passes differ.") ]),

      H1("PART I — VICE CHAIR ST. PIERRE AT 26 TITUS AVENUE"),
      P("Fourteen statements are set out below. Each is measured against what the applicant submitted in writing, what witnesses said at the hearing, and what the ordinance provides. They fall into three groups: facts asserted with no source in the record, opinion offered from the bench in place of evidence, and findings contradicted by the only testimony on the point."),

      H2("A. Facts and figures with no source in the record"),
      N([ b("Slope. "), r("“I do think this property has some very unique characteristics. 18% of it has slope that's undevelopable by ordinance.” (1:56:07), repeated in findings as “a lot of slopes, including 18% that is undevelopable based on the city's calculation of the slope review.” (1:57:48.) No witness testified to a percentage. The figure is the Zoning Review's lot-area arithmetic: 60,406 SF less 10,922 SF for slopes equals 49,484 SF, and 10,922 is 18.1% of the gross. That deduction is how the ordinance computes buildable area on any sloped parcel. It is not a finding that land is undevelopable, and the same deduction was applied to the applicant's own five-lot plan, which still yields five conforming lots.") ]),
      N([ b("Traffic safety. "), r("“By removing curb cuts into Calef, I think we improve safety tremendously” (1:56:13), and in findings, the entrance “off of Titus Avenue, which is in general safer to turn on to than the busier Calef.” (1:58:25.) No traffic count, sight-distance analysis, crash data, or professional opinion is in the file. The applicant said only that four driveways would be a “difficulty” and that Calef is “a heavily traveled road.” (1:09:04.) The Titus-versus-Calef comparison was made by no one but the Vice Chair.") ]),
      N([ b("Uniqueness from experience. "), r("“I don't think we've ever seen in my years on zoning another instance of properties that organically have such a large buffer.” (1:57:04.) A comparison to every other case he has heard is evidence from the member's own memory. It cannot be tested, and it was offered as the ground for finding the parcel unique.") ]),
      N([ b("Lot size as uniqueness. "), r("“It is singularly unique in its size at 1.1 acre.” (1:57:22.) Nothing in the record compares this parcel to others. The applicant's own exhibit describes the complex across the street as “approximately two acres,” larger than this one. A larger lot also cuts against hardship rather than for it: more land means more development capacity, not less.") ]),
      N([ b("Enforced buffer. "), r("“Some of the primary concerns that we hear over and over are addressed by the enforced buffer in a plan development such as this.” (1:56:02.) No landscape plan or buffer design was submitted. The Zoning Review lists a Type 2 buffer as “Can comply,” which records a possibility, not a proposal. An abutter had told the Board the opposite minutes earlier: “There's no plan that shows how far back he's going to go. Is he going to go right up to that 25 feet and take all the trees there?” (1:28:28.)") ]),

      H2("B. Opinion supplied from the bench"),
      N([ b("Property values. "), r("“Also, I am a real estate broker, and I'm not aware of any circumstance where a development of this nature in Manchester has diminished a property around it. I've never seen a report or evidence of that. In general, reasonably well thought out development increases values.” (1:59:02.) This came roughly eight minutes after the applicant's engineer, asked directly by Member Carnevale whether he had obtained a broker price opinion, answered “so no, we did not,” and offered to get one “if the board felt that that was needed.” (1:51:22.) The Board did not ask for one. A member then supplied the opinion the applicant had not obtained.") ]),
      N([ b("Best plan. "), r("“My overall thought on this is that I do believe this is the best plan for this lot.” (1:57:18.) Whether a proposal is the best available plan is not among the five criteria. The Board's function is not to select among possible developments.") ]),
      N([ b("Effort as evidence. "), r("“I think a tremendous amount of thought has been put into this, further evidenced by the applicant taking an additional month to rework and reduce counts.” (1:59:17.) The applicant reduced its requests because the City's review found additional violations and it chose to correct three of them. Bringing a plan closer to compliance is not evidence on any statutory criterion.") ]),
      N([ b("The comparative frame. "), r("“So when I weigh these, I look at, if they're allowed to do or say they did do those five houses, is that more in benefit of safety? Is it more in benefit of the neighbors, of the spirit?” (1:56:20.) This weighs which of two developments the Board prefers. The statutory question under RSA 674:33, I(b)(2) is whether the property can be reasonably used in conformance, not which use is better.") ]),
      N([ b("Hardship to the applicant. "), r("“I do believe literal enforcement creates an unnecessary hardship for the applicant.” (1:59:41.) The statute asks whether hardship arises from special conditions of the property. Hardship to the owner is the thing the statute declines to measure.") ]),

      H2("C. Findings contradicted by the testimony"),
      N([ b("On-street parking. "), r("Findings: allowing the planned development “reduces the need for curb cuts on Calef Road and preserves existing on-street parking.” (1:58:13.) Two witnesses told the Board there is little on-street parking on Calef to preserve. Kate Markey: “Anything south of that, you'll notice if you drive there, there's big no parking signs.” (1:26:23.) Jennifer Allard: “No one can park on Calef. You're not allowed to park on Calef.” (1:32:52.)") ]),
      N([ b("The 25 feet. "), r("Before public comment, a member thanked the applicant for “your work to give the neighbors the 25 feet.” (1:20:45.) "), flag("[Confirm speaker.]"), r(" Jennifer Allard answered directly: “I actually got a lawyer and went to court and we won our half of the street. They didn't give us a half of the street. We won our half, they got the other half. So they didn't give us anything.” (1:31:29.) The findings later softened this to “whether through the applicant or the other neighbors' efforts” (1:57:58) but still counted the buffer as a benefit of the proposal.") ]),
      N([ b("The buffer is on other people's land. "), r("The 130 to 135 feet of woods relied on throughout lies in the rear yards of the Mystic Street owners, not on the applicant's parcel. The applicant's own engineer conceded it: “Now, of course, they have the right to develop that or expand that or cut that.” (1:14:03.) Two of the owners of that land testified in opposition. A buffer on a neighbor's land that the neighbor may remove tomorrow is neither permanent nor a condition of the subject property.") ]),
      N([ b("Transitional area. "), r("“I think this area is a transitional area in that neighborhood” (1:56:31), and in findings, “several other mixed or high density uses including the large development to the south, the cemetery and the Zion School.” (1:58:51.) A cemetery is not a high-density use; the applicant's engineer said of it that “obviously no homes or anything will be built really in that area.” (1:11:04.) More important, “transitional area” is not a designation this parcel carries. Table 3.3-A of the Land Use Code assigns that role to the R-2 district, which “forms a loose band around the more densely developed areas of the City, transitioning between mixed-use centers and the lower densities of the single-family districts.” R-1B's stated intent is “to maintain higher-density neighborhoods of single-family, detached dwellings.”") ]),

      H1("PART II — THE TITUS APPLICANT'S ATTEMPT ON THE FIVE CRITERIA"),
      P([ b("Threshold observation. "), r("The applicant never addressed the five criteria on the record. At the close of his presentation the engineer said: “Obviously I wrote up all the criteria specifically. I'm happy to go through that or read that in if needed, but I can turn it back to the board for any questions before we get to that stage.” (1:19:53.) No member asked him to. The hearing moved to public comment, then rebuttal, then deliberation. The applicant's entire criteria showing is therefore the two-page Dubay Group memorandum of May 20, 2026, supplemented by what the engineer and owner volunteered in rebuttal.") ]),
      P([ b("Second threshold observation. "), r("The Titus application cites no case law. The South Lincoln application, heard immediately before and denied, cites "), i("Chester Rod & Gun Club"), r(" and "), i("Harborside Associates"), r(" and applies them to facts.") ]),

      H2("Criterion 1 — Public interest"),
      P("Written: the neighborhood “comprises of a mix of various uses” and the project is a “reasonable transition.” Oral: an aerial exhibit of surrounding uses. The controlling test is whether the variance would conflict with the ordinance's basic zoning objectives unduly and in a marked degree. The applicant never identified the R-1B district's objectives and never measured the proposal against them. No evidence on health, safety, or welfare was offered. Method does not conform to the standard."),

      H2("Criterion 2 — Spirit of the ordinance"),
      P("Written: “The spirit of the zoning Ordinance in the R-1B zone is to provide higher density residential neighborhoods.” Oral, from the owner: “We're not looking to do a commercial development within a residential neighborhood. So we are in the spirit of the ordinance by having residential within the residential zone.” (1:47:55.)"),
      P("Both formulations fail. The Code's own statement of intent for R-1B is “to maintain higher-density neighborhoods of single-family, detached dwellings.” The applicant quoted the first half and dropped the operative half. And “residential in a residential zone” cannot be the test: Table 4.3-A lists Single Family, Two-Family, Multifamily and Mixed-Use as separate uses with separate district permissions precisely because “residential” is not one category. If that argument were sound, no use variance in any residential district could ever fail this criterion. Method does not conform to the standard."),

      H2("Criterion 3 — Substantial justice"),
      P("Written, in full: “The benefits to the applicant in constructing residential which is far more conducive to the property provides substantial justice.” The governing rule is that any loss to the individual not outweighed by a gain to the general public is an injustice. The applicant weighed only its own benefit, which is the one thing this criterion does not measure. The showing is also self-defeating: the same memo states the property can support five conforming lots, so there is no loss to weigh. Method does not conform to the standard."),

      H2("Criterion 4 — Surrounding property values"),
      P("Written, in full: there is “ample buffering” and the project “would not negatively affect surrounding existing properties.” Oral: asked whether he had obtained a broker price opinion, the engineer answered “so no, we did not” (1:51:22) and offered the 130 to 135 feet of woods as the substitute. The burden on this criterion is the applicant's. No appraisal, market study, or comparable sale was produced. The buffer relied on sits on land the applicant does not own and may be cleared by its owners at will, as the engineer conceded. No evidence was offered at all."),

      H2("Criterion 5 — Unnecessary hardship"),
      P("Written, branch (A)(i): “The intent of the Ordinance in this case is to provide higher density residential neighborhoods and, based on the surrounding properties in the immediate vicinity, the proposed townhouses fit well into the neighborhood while providing reasonable density in-kind with the area.” That describes the neighborhood and the proposed use. It says nothing about this land. The statute's threshold is special conditions of the property that distinguish it from other properties in the area."),
      P("Written, branch (A)(ii): the townhouses “work well with the existing sloped topography,” avoid multiple curb cuts, and the site “can accommodate all appropriate infrastructure and meet all applicable setbacks.” This argues the proposed use is reasonable, which is only the second half of branch (A). The first half, that no fair and substantial relationship exists between the ordinance's general purposes and its application here, is never addressed."),
      P([ b("The oral case, and a contradiction that matters. "), r("In rebuttal the engineer moved to branch (B), citing “the slopes, water, driveways on Calef” (1:53:19). He then conceded: “If you looked at just the square footages, this lot would support more than what we're showing here, just physically based on buildable area divided by 6,000. What do you have for house lots? You have more than that.” (1:53:48.) And then: “If you could have nine single family homes here by right and you can't get more than one or two, is that a reasonable use of the property? I would argue that it isn't.” (1:54:25.)") ]),
      P([ flag("This is the sharpest inconsistency in the record."), r(" The applicant's written memorandum says the parcel “can support five (5) single family home lots meeting the underlying zoning,” and its sealed By-Right Subdivision Plan shows five lots, each with more than 6,000 square feet of buildable area. Orally, and with no supporting drawing, grading analysis, or cost estimate, the engineer told the Board only one or two houses could actually be built. The owner repeated it: “As Mr. MacGuire stated, the hardship is the steep slopes. We can't essentially build the houses. We were showing what it was. But you can't build them. This you can build.” (1:48:17.) The Board was asked to disbelieve the applicant's own stamped exhibit on the applicant's unsupported say-so, and it did.") ]),
      P([ b("The density argument. "), r("The engineer also argued that under R-M standards the buildable area would permit seventeen townhouse units, and that townhouses are allowed three stories and forty feet, so the height requests “would meet the intent of that criteria.” (1:18:26 to 1:19:33.) Both arguments apply the standards of a district this parcel is not in. That is an argument for rezoning under RSA 675, which is a legislative act of the Board of Mayor and Aldermen. It is not a hardship, and it is not a variance argument. Note also that the applicant passed over the standard that does apply: §8.1.2 requires 6,000 square feet per planned-development unit, which on 49,484 square feet yields eight.") ]),

      H1("PART III — 218 SOUTH LINCOLN STREET, THE FULL BOARD"),
      P("The South Lincoln case was heard immediately before Titus Avenue. The applicant sought relief from the same ordinance section, §4.3-A.1.C, to add one dwelling unit to an existing two-family house in the R-2 district, where two-family dwellings are permitted by right. It was denied unanimously."),

      H2("Vice Chair St. Pierre"),
      B([ b("Tested the applicant's technical claim rather than supplying it. "), r("He questioned the electrical panels: “The three panels, though, it's house unit one and unit two, correct? So you need four at a third unit?” (0:33:51.) In deliberation he used that to reject the applicant's central factual assertion: “There's no evidence that this was ever intended to be a third. I recognize that the applicant's stating that, but a house panel is going to be needed to operate the one boiler system with the multi-zone. So that's not going to fly with me either.” (1:01:01.)") ]),
      B([ b("Demanded evidence. "), r("“So there's no evidence here in my mind that the spirit's observed or any substantial justice is done, let alone a hardship.” (1:01:24.)") ]),
      B([ b("Rejected a configuration hardship. "), r("“The inability to subdivide's not a hardship.” (1:00:04.) "), flag("[Both transcription passes continue “it's absurd”; the first pass does not. Verify.]") ]),
      B([ b("Rejected self-created hardship. "), r("“Just the fact that they overbuilt this house, which has been stated that the applicant had their own hand in, that's not a hardship.” (1:01:11.)") ]),
      B([ b("Measured spirit by the district's stated intent and by counting surrounding uses. "), r("“The specific spirit of that ordinance is a mix of single and duplexes. So when we look at the applicant's own exhibit, they've submitted that there's 41 singles, five two families, and one three on their own exhibit. So this is clearly out of the spirit of the ordinance by definition, but it's also not in keeping with the character of this neighborhood.” (1:00:18.)") ]),
      B([ b("Held long-standing actual use above original design intent. "), r("“It's existed as a two family for well over 50 years, so that kind of mutes that point in my book.” (1:01:41.)") ]),
      B([ b("Pressed the applicant on stewardship. "), r("“The property's been allowed to get into a condition that's concerning… what was the reason that it was allowed to degrade to its current state?” (0:36:38.) He also pressed the owner-occupancy representation: “So that's not owner-occupied as you're presenting?… Anything can or will be, but that's not what it is.” (0:36:24.)") ]),
      B([ b("On property values, he relied on record evidence. "), r("“I tend to agree that a three family may not diminish the values of the property around it. So for that, I don't believe that the property values will be diminished.” (1:04:18.) The South Lincoln applicant had retained a broker and put the opinion in evidence at Exhibit J.") ]),

      H2("Member Carnevale"),
      P("He applied one test in both cases. At South Lincoln: “It's my understanding that when we have that fifth prong of hardship, it can't override the fundamental purpose of what something's zoned for. And it seems here that that's being attempted to use to override the fact that three families aren't allowed by then claiming a hardship on a somewhat inventive approach to characterizing it as a three family.” (1:02:11.) At Titus, an hour later: “I'm having a tough time seeing how an actual hardship exists that would override the prime instruction, which is that this is not an area that's zoned for townhouses.” (1:50:18.) He also asked the only evidentiary question either applicant faced on criterion 4. He voted to deny both. His reasoning is consistent."),

      H2("The Chair, Member Catherine, Member Scott"),
      B("The Chair ran both hearings procedurally and in both asked Vice Chair St. Pierre to state the findings of fact. When a member asked the Vice Chair to slow down during the Titus findings, the answer was “I got you later.” (1:58:33.)"),
      B("Member Catherine asked record-based questions at South Lincoln about the claimed earlier variance and the age of the electrical panels. She seconded the denial at South Lincoln and the approval at Titus. No reasoning of hers is recorded at Titus."),
      B("Member Scott is recorded as declining to comment at Titus (1:57:36). A member other than the Vice Chair followed up on the electrical panels at South Lincoln (0:34:34), opening “Craig makes a good point.” That speaker is not identified on the recording."),

      H2("The South Lincoln applicant's method"),
      P("Attorney Sullivan's packet quotes the controlling standard for criteria 1 and 2 and applies it, retains a broker for criterion 4, and addresses each criterion in writing. On criterion 5 his formulation was circular: “One of the alternatives to the hardship criteria is if it's a reasonable use, and that use can't be done without relief, that's a hardship.” (0:58:41.) That would make every variance self-proving, and Member Carnevale identified the flaw. The special conditions offered, a corner lot, the largest lot in the area, an inability to subdivide, and a building configured for three units, are mostly not conditions of the land. The Board was right that hardship was not shown."),
      P([ b("The comparison that matters. "), r("The South Lincoln attorney told the Board: “In terms of the property value, I have a broker's opinion of a well-known broker in the area… I am not a broker. But I rely on somebody else's opinion who is a broker of knowledge and skill and experience.” (0:54:45.) An hour later the Titus applicant produced no such opinion, and a member of the Board announced “I am a real estate broker” and supplied one. The applicant who retained an expert lost. The applicant who did not was given one from the table.") ]),

      H1("PART IV — THE TWO CASES SIDE BY SIDE"),
      N("Same ordinance section. Both applicants sought relief from §4.3-A.1.C, Multifamily Dwellings, under the Land Use Code effective March 1, 2026."),
      N("Opposite scale. South Lincoln: one added unit, in a district where two-family dwellings are permitted by right, with no change to the building footprint and one added door. Titus Avenue: thirteen units and two new buildings, in a district where only single-family detached dwellings are permitted, with six separate variances including building type, lot area, and height in stories and feet."),
      N("Opposite evidence. South Lincoln produced a named broker's opinion, cited controlling case law, and addressed each criterion in writing and orally. Titus produced no broker's opinion, cited no case law, and never addressed the criteria on the record at all."),
      N("Opposite treatment of self-created difficulty. At South Lincoln, a building the applicant had a hand in configuring could not create hardship. At Titus, the four Calef Road driveways that were said to make the conforming plan unworkable appear only on a drawing the applicant itself prepared, and the parcel fronts on two streets."),
      N("Opposite treatment of the district's stated intent. At South Lincoln the Vice Chair measured the spirit of the ordinance against the R-2 district's intent and counted the surrounding housing types from the applicant's own exhibit. At Titus he substituted “transitional area,” a description the Code gives to a different district, and did not count the surrounding single-family homes on the applicant's exhibit."),
      N("Opposite treatment of outside knowledge. At South Lincoln the Vice Chair's technical knowledge was used to test and reject the applicant's claim. At Titus his professional knowledge was used to supply the applicant's missing proof. In both cases the outside knowledge decided the criterion."),
      N("Opposite outcomes. South Lincoln denied unanimously. Titus approved four to one, Member Carnevale dissenting on hardship, property values and spirit."),

      H1("PART V — WHAT THIS SUPPORTS, AND WHAT IT DOES NOT"),
      H2("Strongest points"),
      B("The applicant's oral claim that only one or two houses can be built contradicts its own written memorandum and its own sealed plan, and was unsupported. This is new and it goes to the criterion that decided the case."),
      B("A Board member supplied expert opinion on property values after the applicant admitted it had none, minutes after the same Board denied a smaller application whose applicant had retained an actual broker."),
      B("The safety finding rests on a comparison no witness made, on a record where the City's own review records “No Information” for intersection visibility, and against the only testimony offered on the subject."),
      B("The inconsistency between the two cases is documented, on the same night, largely in the same member's own words."),

      H2("Weaker points, to use with care"),
      B("Demeanor. The warmth toward one applicant and the sharpness toward the other is real on the recording but proves nothing on its own. It is context, not a ground."),
      B("Prejudgment. “As the applicant had, beat me to” shows arguments prepared in advance. Board members may prepare. It supports a request that the Vice Chair disclose any outside contact; it does not by itself establish disqualification."),
      B("The “it's absurd” phrase at South Lincoln is not yet verified and should not be quoted until it is."),
      B("Speaker attributions are inferred from first names on the recording and must be confirmed against the video."),

      H2("Next steps"),
      B("Confirm every attribution and the two flagged passages against the video."),
      B("Obtain the City's certified recording and the written decision through the RSA 91-A request."),
      B("Decide with counsel which of these findings go into the motion for rehearing and which are held for an appeal, where the standard is whether the decision was unlawful or unreasonable on the record."),

      new Paragraph({ border: { top: { style: BorderStyle.SINGLE, size: 6, color: "000000" } }, spacing: { before: 180, after: 0 },
        children: [ new TextRun({ text: "Prepared for Nickolas J. Levasseur, 30 Mystic Street, Manchester, NH 03103. Working paper; quotations are machine transcriptions of the City's recording and should be verified before any use in a filing.", italics: true, size: 15 }) ] }),
    ]
  }]
});
Packer.toBuffer(doc).then(buf => require('fs').writeFileSync('../documents/Titus_Ave_Hearing_Analysis.docx', buf));
